Controllers/ClientController.cs
using ERP.Models;
using ERP.Repositories.Interfaces.Clients;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ERP.Controllers {
    public class ClientController : Controller {

        private readonly IClientRepository _clientRepository;

        public ClientController(IClientRepository clientInterface) {
            _clientRepository = clientInterface;
        }

        public async Task<IActionResult> Index() {

            var clients = await _clientRepository.GetCLients();

            var viewModel = new ClientIndexViewModel {
                Clients = clients,
                NewClient = new Client()
            };

            return View(viewModel);
        }

      
        public IActionResult CreateClient() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateClient(Client client) {
            if (ModelState.IsValid) {

                await _clientRepository.CreateClientAsync(client);

                return RedirectToAction("Index");
            }

            return View(client);
            
        }

        public async Task<IActionResult> EditClient(int id) {
            Client client = await _clientRepository.GetClientByIdAsync(id);
            return View(client);
        }


        [HttpPost]
        public async Task<IActionResult> EditClient(Client client) {
            if (ModelState.IsValid) {

                var updatedClient = await _clientRepository.EditClientAsync(client);

                if (updatedClient == null)
                    return NotFound();

                return RedirectToAction("Index");
            }

            return View(client);

        }

    
        public async Task<IActionResult> DeleteClient(int id) {
            var deleted = await _clientRepository.DeleteClientAsync(id);
            if (!deleted)
            return NotFound();

            return RedirectToAction("Index");
        }

      
        public async Task<IActionResult> Delete(int id) {

            var client = await _clientRepository.GetClientByIdAsync(id);
      

            return View(client);
        }


    }
}

Controllers/ProductController.cs
using ERP.Models;
using ERP.Repositories.Interfaces.Products;
using ERP.Repositories.Products;
using Microsoft.AspNetCore.Mvc;
using System.Net.WebSockets;
using System.Threading.Tasks;

namespace ERP.Controllers {
    public class ProductController : Controller {

        private readonly IProductRepository _productRepository;

        public ProductController(IProductRepository productRepo) {
            _productRepository = productRepo;
        }
        public async Task<IActionResult> Index() {

            var products = await _productRepository.GetAllAsync();

            return View(products);
        }

        public IActionResult CreateProduct() {
             return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> CreateProduct(Product product) {
            if (!ModelState.IsValid) {
                return BadRequest(ModelState);
            }
            await _productRepository.AddAsync(product);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> EditProduct(int id) {

            Product product = await _productRepository.GetByIdAsync(id);
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> EditProduct(Product product) {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var updatedClient = await _productRepository.UpdateAsync(product);

            if (updatedClient == null)
                return NotFound();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteProduct(int id) {
            var deleted = await _productRepository.DeleteAsync(id);
            if(!deleted)
                return NotFound();

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int id) {
            Product prod = await _productRepository.GetByIdAsync(id);
            return View(prod);
        }
    }
}

Controllers/ReportController.cs
using ERP.Services.Report;
using ERP.Services.Reports;
using FastReport.Data;
using FastReport.Export.PdfSimple;
using FastReport.Web;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Threading.Tasks;

public class ReportController : Controller {
    private readonly ReportService _reportService;
    private readonly IWebHostEnvironment _webHostEnv;

    public ReportController(IWebHostEnvironment webHostEnv, ReportService reportService) {
        _webHostEnv = webHostEnv;
        _reportService = reportService;
    }

    public IActionResult Index() {
        return View();
    }
 
    public async Task<IActionResult> GerarReport() {
        var webReport = new WebReport();
        var mssqlDataConnection = new MsSqlDataConnection();

        webReport.Report.Dictionary.AddChild(mssqlDataConnection);

        webReport.Report.Load(Path.Combine(_webHostEnv.ContentRootPath, "wwwroot/reports",
                                           "SaleReport.frx"));

        var sale = HelperFastReport.GetTable(await _reportService.GetSaleReport(), "SaleReports");
        var prod = HelperFastReport.GetTable(await _reportService.GetProductReport(), "ProdReport");
        var client = HelperFastReport.GetTable(await _reportService.GetClientsReport(), "ClientReports");
        var saleItem = HelperFastReport.GetTable(await _reportService.GetSaleItemsReport(), "SaleItemReport");


        webReport.Report.RegisterData(sale, "SaleReports");
        webReport.Report.RegisterData(prod, "ProdReport");
        webReport.Report.RegisterData(client, "ClientReports");
        webReport.Report.RegisterData(saleItem, "SaleItemReport");
        return View(webReport);
    }

    [Route("SalePDF")]
    public async Task<IActionResult> SalesPDF() {
        var webReport = new WebReport();
        var mssqlDataConnection = new MsSqlDataConnection();

        webReport.Report.Dictionary.AddChild(mssqlDataConnection);

        webReport.Report.Load(Path.Combine(_webHostEnv.ContentRootPath, "wwwroot/reports",
                                           "SaleReport.frx"));

        var sale = HelperFastReport.GetTable(await _reportService.GetSaleReport(), "SaleReports");
        var prod = HelperFastReport.GetTable(await _reportService.GetProductReport(), "ProdReport");
        var client = HelperFastReport.GetTable(await _reportService.GetClientsReport(), "ClientReports");
        var saleItem = HelperFastReport.GetTable(await _reportService.GetSaleItemsReport(), "SaleItemReport");


        webReport.Report.RegisterData(sale, "SaleReports");
        webReport.Report.RegisterData(prod, "ProdReport");
        webReport.Report.RegisterData(client, "ClientReports");
        webReport.Report.RegisterData(saleItem, "SaleItemReport");

        webReport.Report.Prepare();

        Stream stream = new MemoryStream();

        webReport.Report.Export(new PDFSimpleExport(), stream);
        stream.Position = 0;

        //return File(stream, "application/zip", "SalesReport.pdf");
        return new FileStreamResult(stream, "application/pdf");
    }

}

Controllers/SaleController.cs
using ERP.Context;
using ERP.Models;
using ERP.Services.Sales;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP.Controllers {
    public class SaleController : Controller {

        private readonly SaleService _saleService;
        private readonly AppDbContext _context;

        public SaleController(SaleService saleService, AppDbContext context) {
            _saleService = saleService;
            _context = context;
        }

        public async Task<IActionResult> Index() {

            var sales = await _saleService.GetAllAsync();
            return View(sales);
        }

        public  async Task<IActionResult> CreateSale() {
            if (ModelState.IsValid) {
                ViewBag.Clients = await _context.Clients.ToListAsync();
                ViewBag.Products = await _context.Products.Where(p => p.Stock > 0).ToListAsync();
                ViewBag.PaymentMethods = new List<string> { "Dinheiro", "Cartão", "Pix" };

                return View();
            }

            return View();

            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSale(Sale sale) {
            if (!ModelState.IsValid) {
                // Recarrega dropdowns se houver erro
                ViewBag.Clients = await _context.Clients.ToListAsync();
                ViewBag.Products = await _context.Products.Where(p => p.Stock > 0).ToListAsync();
                ViewBag.PaymentMethods = new List<string> { "Dinheiro", "Cartão", "Pix" };
                return View(sale);
            }

            var result = await _saleService.AddAsync(sale);
            if (!result.Success) {
                ModelState.AddModelError("", result.ErrorMessage);
                ViewBag.Clients = await _context.Clients.ToListAsync();
                ViewBag.Products = await _context.Products.Where(p => p.Stock > 0).ToListAsync();
                ViewBag.PaymentMethods = new List<string> { "Dinheiro", "Cartão", "Pix" };
                return View(sale);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditSale(int id) {

            var sale = await _saleService.GetByIdAsync(id);
            if (sale == null) {
                return NotFound();
            }

            // Carregar listas para dropdowns
            ViewBag.Clients = await _context.Clients.ToListAsync();
            ViewBag.Products = await _context.Products.Where(p => p.Stock > 0).ToListAsync();
            ViewBag.PaymentMethods = new List<string> { "Dinheiro", "Cartão", "Pix" };

            return View(sale);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSale(Sale sale) {
            if (ModelState.IsValid) {
                await _saleService.UpdateAsync(sale); 
                return RedirectToAction("Index");
            }

            ViewBag.Clients = await _context.Clients.ToListAsync();
            ViewBag.Products = await _context.Products.ToListAsync();
            ViewBag.PaymentMethods = new List<string> { "Dinheiro", "Cartão", "Pix" };

            return View(sale);
        }

        public async Task<IActionResult> DeleteSale(int id) {
            var delete = await _saleService.DeleteAsync(id);
            if (delete == null )
                return NotFound();

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int id) {

            var client = await _saleService.GetByIdAsync(id);


            return View(client);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ERP</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.3.3/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

</head>

<body>

    @* SOMENTE MOSTRAR O HEADER SE NÃO FOR LOGIN OU REGISTER *@
    @if (!(ViewContext.RouteData.Values["controller"].ToString() == "Account" &&
        (ViewContext.RouteData.Values["action"].ToString() == "Login" ||
        ViewContext.RouteData.Values["action"].ToString() == "Register"))) {
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3 shadow-sm p-3 rounded">
                <div class="container-fluid">

                    <!-- LOGO -->
                    <a class="navbar-brand d-flex align-items-center" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" alt="Logo" width="50" height="30" class="me-2" />
                    </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">

                        <!-- MENU CENTRAL -->
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item mx-2">
                                <a class="nav-link text-dark h5" asp-controller="Home" asp-action="Index">Início</a>
                            </li>

                            <li class="nav-item mx-2">
                                <a class="nav-link text-dark h5" asp-controller="Client" asp-action="Index">Clientes</a>
                            </li>

                            <li class="nav-item mx-2">
                                <a class="nav-link text-dark h5" asp-controller="Product" asp-action="Index">Produtos</a>
                            </li>

                            <li class="nav-item mx-2">
                                <a class="nav-link text-dark h5" asp-controller="Sale" asp-action="Index">Vendas</a>
                            </li>

                            <li class="nav-item mx-2">
                                <a class="nav-link text-dark h5" asp-controller="Report" asp-action="Index">Relatório</a>
                            </li>
                        </ul>

                        <div class="ms-auto d-flex align-items-center">
                            @await Html.PartialAsync("_LoginPartial")
                        </div>

                    </div>

                </div>
            </nav>
        </header>

    }

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2025 - ERP - Desenvolvido por Otávio
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>


    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>